### ISSUE TITLE
Sweep: Update `objectives` in front matter to use arrays.

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#295]
Currently, inside `index.md` files we're using front matter that looks like this:
```toml
+++
title = ': Returning'
headless = true
time = 5
facilitation = false
emoji= '🗄️'
[objectives]
    1='Identify a call site'
    3='Identify the return value evaluated at a call site given its function declaration'
    4='Reuse code to perform the same calculation with different inputs'
    5='Log the return value of a function'
    6='Given a short program, state the number of times a given function is called'
+++
```
As you can see, the objectives are numbered from 1 to 6. However, we want the objectives to be an array that looks like this:
```toml
+++
title = ': Returning'
headless = true
time = 5
facilitation = false
emoji= '🗄️'
objectives=[
  'Identify a call site',
  'Identify the return value evaluated at a call site given its function declaration',
  'Reuse code to perform the same calculation with different inputs',
  'Log the return value of a function',
 'Given a short program, state the number of times a given function is called'
]
+++
```

Please find all the front matter blocks and change the numbered objectives over to an array format instead.

<details open>
<summary>Checklist</summary>

- [X] `scripts/update_front_matter.py` ✅ Commit [`c8c71d0`](https://github.com/CodeYourFuture/curriculum/commit/c8c71d01157b0c4a0f1a796444d4a1c98a243581)
<blockquote>• Import the `os` and `re` modules.
• Define a function `update_front_matter` that takes a file path as an argument.
• In this function, open the file in read mode and read its content into a string.
• Use the `re` module to find the front matter block in the string (it's the part between `+++` and `+++`).
• Within this block, replace the current dictionary representation of objectives with an array representation. This can be done with a regular expression replacement operation.
• Write the modified string back to the file.
• Define a function `traverse_directory` that takes a directory path as an argument.
• In this function, use the `os` module to traverse the directory and its subdirectories.
• For each file encountered, if the file name is `index.md`, call the `update_front_matter` function on it.
• Call the `traverse_directory` function on the `content` directory.</blockquote>

</details>
